#!/bin/bash
#PBS -N runtrain
#PBS -j oe
#PBS -l nodes=1:ppn=1:gpus=1:V100
#PBS -l walltime=24:00:00:00
#PBS -q dept_gpu_16GB

echo Running on `hostname`
echo workdir $PBS_O_WORKDIR
echo ld_library_path $LD_LIBRARY_PATH
export PATH=/usr/bin:$PATH
export LD_LIBRARY_PATH=/net/pulsar/home/koes/dkoes/local/lib:/usr/lib64:/usr/lib/x86_64-linux-gnu:/usr/local/cuda-9.0/lib64
export PYTHONPATH=/net/pulsar/home/koes/dkoes/local/python:$PYTHONPATH

cd $PBS_O_WORKDIR
python /net/pulsar/home/koes/lmt72/scripts/train.py -m dn_121.model -p /net/pulsar/home/koes/dkoes/PDBbind/refined-set/affinity_search/types/all_0.5_0_ -t 1000 --reduced -o python /net/pulsar/home/koes/lmt72/DenseNets/DenseNets/four/dn_121 -i 500000 --clip_gradients 10
wait

$cmd

exit
